name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv install

    - name: Test with pytest
      run: |
        pipenv run pytest -v --cov=CODE_DIRECTORY --cov-report=html

    - name: Commit files
      run: |
        git add .
        git commit -m "Coverage"
        git push
